/****************************************************************************
**
** Copyright (C) 2014
**
** This file is generated by the Magus toolkit
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
** "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
** LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
** A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
** OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
** SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
** LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
** DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
** THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
** (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
** OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE."
**
****************************************************************************/

#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QCloseEvent>
#include <QMainWindow>
#include <QMenu>
#include <QAction>
#include <QMessageBox>
#include <QToolBar>
#include <QTableWidget>

QT_BEGIN_NAMESPACE

QT_END_NAMESPACE

static const QString POSTFIX = QString("_conv");
static const QString MODERN_DESKTOP_WITH_NMAP_OPTIONS = QString(" -v2 -e -t -ts 4 -O puqs ");
static const QString MODERN_DESKTOP_WITHOUT_NMAP_OPTIONS = QString(" -v2 -e -O puqs ");
static const QString GLES2_WITH_NMAP_OPTIONS = QString(" -v2 -e -t -ts 4 -O qs ");
static const QString GLES2_WITHOUT_NMAP_OPTIONS = QString(" -v2 -e -O qs ");

/****************************************************************************
 MainWindow is the main container window
 ***************************************************************************/
class MainWindow : public QMainWindow
{
	Q_OBJECT

	public:
		MainWindow(void);
		~MainWindow(void);
		bool mIsClosing;

	private slots:
        // File
        void doImportMenuAction(void);
        void doSetOutputDirMenuAction(void);
        void doConvertMenuAction(void);
        void doClearMenuAction(void);
        void doQuitMenuAction(void);

        // Options
        void doPostFixMenuAction(void);
        void doOptionsModernDesktopWithNmapMenuAction(void);
        void doOptionsModernDesktopWithoutNmapMenuAction(void);
        void doOptionsGles2WithNmapMenuAction(void);
        void doOptionsGles2WithoutNmapMenuAction(void);

	private:
		void createActions(void);
		void createMenus(void);
		void createToolBars(void);
		void createStatusBar(void);
		void createDockWindows(void);
		void closeEvent(QCloseEvent* event);

        QMenu* mFileMenu;
        QMenu* mOptionsMenu;
        QAction* mImportMenuAction;
        QAction* mSetOutputDirMenuAction;
        QAction* mConvertMenuAction;
        QAction* mClearMenuAction;
        QAction* mQuitMenuAction;
        QAction* mPostFixMenuAction;
        QAction* mOptionsModernDesktopWithNmapMenuAction;
        QAction* mOptionsModernDesktopWithoutNmapMenuAction;
        QAction* mOptionsGles2WithNmapMenuAction;
        QAction* mOptionsGles2WithoutNmapMenuAction;
        QTableWidget* mTable;
        QString mOutputFolder;
        QString mPostfix;
        QString mParameters;
        unsigned int mRunNumber;
};

#endif

